import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { performRAG, cleanDocumentText } from '@/lib/ragSystem';

// Initialize Gemini
let genAI: GoogleGenerativeAI | null = null;
function getGeminiClient() {
  if (!genAI && process.env.GEMINI_API_KEY) {
    genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  }
  return genAI;
}

/**
 * POST /api/escalations/suggest-reply
 * Agent AI Copilot - Generates a 1-click resolution draft for support agents
 * based on conversation history, customer question, and Pinecone vector search.
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { question, attemptedAnswer, triggerReason, urgency } = body;

    if (!question || typeof question !== 'string') {
      return NextResponse.json(
        { success: false, error: 'Customer question is required' },
        { status: 400 }
      );
    }

    const client = getGeminiClient();
    if (!client) {
      return NextResponse.json(
        { success: false, error: 'AI service not configured (missing GEMINI_API_KEY)' },
        { status: 500 }
      );
    }

    // 1. Retrieve relevant knowledge base chunks from Pinecone
    let kbContext = '';
    let sources: Array<{ documentName: string; score: number }> = [];
    try {
      const ragResult = await performRAG(question, { topK: 4, minScore: 0.22 });
      if (ragResult.hasContext && ragResult.sources.length > 0) {
        sources = ragResult.sources.map(s => ({
          documentName: s.documentName,
          score: Math.round(s.score * 100)
        }));

        kbContext = ragResult.sources
          .map((s, idx) => `[Source ${idx + 1}: ${s.documentName} (Match: ${Math.round(s.score * 100)}%)]\n${cleanDocumentText(s.text)}`)
          .join('\n\n');
      }
    } catch (ragErr) {
      console.warn('[Copilot API] RAG retrieval warning:', ragErr);
    }

    // 2. Query Gemini 2.5 Flash with Copilot instructions
    const model = client.getGenerativeModel({
      model: 'gemini-2.5-flash',
      generationConfig: {
        temperature: 0.4,
        maxOutputTokens: 2048,
        responseMimeType: 'application/json'
      }
    });

    const prompt = `You are a Senior Customer Support Specialist and AI Copilot for Knowrex.
A customer opened an escalated support ticket. Help the human agent draft an empathetic, professional, and definitive resolution that can be sent to the customer or saved to the company knowledge base.

CUSTOMER QUESTION / ISSUE:
"${question}"

ESCALATION DETAILS:
- Trigger Reason: ${triggerReason || 'Human agent review needed'}
- Urgency: ${urgency || 'medium'}
${attemptedAnswer ? `- Previous Bot Attempt: "${attemptedAnswer}"` : ''}

${kbContext ? `OFFICIAL KNOWLEDGE BASE CONTEXT (Pinecone Vectors):\n${kbContext}` : 'Note: No direct documentation matched in knowledge base. Provide best-practice guidance.'}

RESPONSE FORMAT:
Return a JSON object with:
{
  "suggestedAnswer": "A complete, friendly, and professional response addressed to the customer with specific actionable details, timelines, and next steps.",
  "category": "One of: 'billing', 'technical', 'product', 'account', 'policy', 'general'",
  "tags": ["2 to 4 relevant tags for indexing"],
  "internalNote": "Brief 1-sentence note for internal audit"
}`;

    const result = await model.generateContent(prompt);
    const textResponse = result.response.text();

    let parsedResult;
    try {
      parsedResult = JSON.parse(textResponse);
    } catch {
      // Fallback if JSON formatting is slightly off
      parsedResult = {
        suggestedAnswer: textResponse,
        category: 'general',
        tags: ['support', 'escalation'],
        internalNote: 'Generated by AI Copilot'
      };
    }

    return NextResponse.json({
      success: true,
      suggestedAnswer: parsedResult.suggestedAnswer,
      category: parsedResult.category || 'general',
      tags: parsedResult.tags || [],
      internalNote: parsedResult.internalNote,
      sourcesUsed: sources
    });
  } catch (error: any) {
    console.error('[Copilot API] Error generating suggested reply:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to generate suggested reply' },
      { status: 500 }
    );
  }
}
